### ISSUE TITLE
New RECFAST doesn't like dual-numbers

### ISSUE THREAD

**Issue by JaimeRZP** [xzackli/Bolt.jl#88] opened 2023-06-01 08:40 UTC
Dear Jamie and Zack

After the latest update I get the following error when I try to ForwardDiff.jl through RECFAST:
```
Got exception outside of a @test
  MethodError: no method matching Bolt.RECFAST(::Bolt.Background{ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}, Interpolations.ScaledInterpolation{ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}, 1, Interpolations.BSplineInterpolation{ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}, 1, OffsetArrays.OffsetVector{ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}, Vector{ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}}}, Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}}, Tuple{Base.OneTo{Int64}}}, Interpolations.BSpline{Interpolations.Cubic{Interpolations.Line{Interpolations.OnGrid}}}, Tuple{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Int64, ::Int64, ::ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}, ::ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}, ::ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}, ::ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}, ::ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}, ::ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}, ::ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}, ::ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}, ::ForwardDiff.Dual{ForwardDiff.Tag{var"#lin_Bolt#19"{Vector{Float64}}, Float64}, Float64, 1}, ::Float64, ::Float64, ::Float64)

  Closest candidates are:
    Bolt.RECFAST(::AB, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::Any, ::Any, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T) where {T, AB<:(Bolt.AbstractBackground{T, IT} where IT<:(Interpolations.AbstractInterpolation{T, 1}))}
```

Code to replicate the error:
```
function get_Bolt_pk0(Ω_c)
    𝕡 = Bolt.CosmoParams(Ω_c = Ωc)
    bg = Background(𝕡)
    𝕣 = Bolt.RECFAST(bg=bg, Yp=𝕡.Y_p, OmegaB=𝕡.Ω_b,OmegaG=𝕡.Ω_r)
    ih = IonizationHistory(𝕣, 𝕡, bg)
    # bg.H₀ = 0.00023349 [1/Mpc] 
    kmin,kmax,nk = 0.5*0.00023349,30000*0.00023349,70 
    ks_Bolt = log10_k(kmin,kmax,nk)
    pL = [plin(k,𝕡,bg,ih) for k in ks_Bolt]
    return ks_Bolt, pL
end
ForwardDiff.derivative(get_Bolt_pk0, 0.25)
```
(not exactly what I am running but should the trick)

The speed up is amazing though!!!

Thanks a lot, 
Jaime

**Comment by jmsull** [comment] 2023-06-01 16:13
cf [this version of the file](https://github.com/xzackli/Bolt.jl/blob/e8705835a5aa7a413aa67c1632774a8d7b735499/src/ionization/recfast.jl#L22) (which works)

**Comment by xzackli** [comment] 2023-06-02 20:40
I think the issue is that the new RECFAST wants the background as a non-kwarg, 

```julia
𝕣 = Bolt.RECFAST(bg; Yp=𝕡.Y_p, OmegaB=𝕡.Ω_b,OmegaG=𝕡.Ω_r)
```

**Comment by JaimeRZP** [comment] 2023-06-06 15:32
Problem solved using the new syntax. Thank you so much!
Anoher related question though, are we surprised that the derivative of Bolt.jl looks so different than the one from Eis&Hu?
![image](https://github.com/xzackli/Bolt.jl/assets/39957598/bc924f33-5a44-4011-ac71-bef38ee05307)

**Comment by jmsull** [comment] 2024-03-07 22:24
Gonna close this given my test here - there may be a problem with the Limberjack implementation that causes the discrepancy above

**Closed by jmsull** 2024-03-07 22:24 UTC
